name: Demo GitHub Actions Workflow

on:
  push:

jobs:
  Discover-GitHub-Actions-Workflows:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub action by Archit
        run: echo "Hello world, this is Action"
      - name: Echo GitHub Event
        run: echo "${{ github.event_name }} event automatically triggered this job."

      - run: echo "A ${{ runner.os }} server hosted by GitHub has this job running"

      - run: echo "Details of your repository repo-name ${{ github.repository }} and branch name is${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checking out the repositoryâ€™s code
        uses: actions/checkout@v3

      - run: echo "The runner has cloned your ${{ github.repository }} repository."

      - run: echo "The workflow can now test your code with the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "This job has a ${{ job.status }} status."
